feat(Actions/Auto-Approve): terminate if PR is unknown

diff --git a/actions/maintenance/auto-approve-pr/action.yaml b/actions/maintenance/auto-approve-pr/action.yaml
--- a/actions/maintenance/auto-approve-pr/action.yaml
+++ b/actions/maintenance/auto-approve-pr/action.yaml
@@ -50,6 +50,11 @@ runs:
         BASE_REPO=$(jq -r '.base.repo.full_name' pr.json)
         AUTHOR_ID=$(jq -r '.user.id' pr.json)
 
+        if [[ -z "$HEAD_REF" || -z "$HEAD_REPO" || -z "$BASE_REPO" || -z "$AUTHOR_ID" ]]; then
+          echo "::error::Failed to parse PR URL: $PR_URL"
+          exit 1
+        fi
+
         echo "head_ref=$HEAD_REF" >> "$GITHUB_OUTPUT"
         echo "head_repo_full_name=$HEAD_REPO" >> "$GITHUB_OUTPUT"
         echo "base_repo_full_name=$BASE_REPO" >> "$GITHUB_OUTPUT"
